#!/bin/bash

function mostrar_menu() {
    echo "Seleccione una opción:"
    echo "1. Crear directorio"
    echo "2. Listar directorios"
    echo "3. Crear un archivo"
    echo "4. Ver el contenido de un archivo"
    echo "5. Eliminar un archivo"
    echo "6. Codificar en base64"
    echo "7. Decodificar base64"
    echo "8. Buscar archivos por nombre"
    echo "9. Mover archivos entre directorios"
    echo "10. Copiar archivos"
    echo "11. Salir"
}

function crear_directorio() {
    read -p "Ingrese el nombre del nuevo directorio: " nombre_directorio
    mkdir -p "$nombre_directorio"
    echo "Directorio '$nombre_directorio' creado."
}

function listar_directorio() {
    read -p "Ingrese el nombre del directorio: " nombre_directorio
    if [ -d "$nombre_directorio" ]; then
        cd "$nombre_directorio" || return
        ls -las
        cd - > /dev/null
    else
        echo "Directorio no encontrado"
    fi
}

function crear_archivo() {
    read -p "Ingrese el nombre del archivo a crear: " nombre_archivo
    read -p "Ingrese el contenido: " contenido_archivo
    echo "$contenido_archivo" > "$nombre_archivo"
    echo "Archivo '$nombre_archivo' creado."
}

function ver_archivo() {
    read -p "Ingrese el nombre del archivo que quiere ver: " nombre_archivo
    if [ -f "$nombre_archivo" ]; then
        cat "$nombre_archivo"
    else
        echo "Archivo no encontrado"
    fi
}

function eliminar_archivo() {
    read -p "Ingrese el nombre del archivo que quiere eliminar: " nombre_archivo
    if [ -f "$nombre_archivo" ]; then
        rm "$nombre_archivo"
        echo "Archivo '$nombre_archivo' eliminado exitosamente."
    else
        echo "Archivo no encontrado"
    fi
}

function codificar_base64() {
    read -p "Ingrese el nombre del archivo que quiere codificar: " nombre_archivo
    if [ -f "$nombre_archivo" ]; then
        base64 "$nombre_archivo" > "$nombre_archivo.b64"
        echo "El archivo codificado se guardó como '$nombre_archivo.b64'."
    else
        echo "Archivo no encontrado"
    fi
}

function decodificar_base64() {
    read -p "Ingrese el nombre del archivo a decodificar sin la extensión .b64: " nombre_archivo
    if [ -f "$nombre_archivo.b64" ]; then
        base64 -d "$nombre_archivo.b64" > "$nombre_archivo.decodificado"
        echo "El archivo decodificado se guardó como '$nombre_archivo.decodificado'."
    else
        echo "Archivo codificado no encontrado"
    fi
}

function buscar_archivos() {
    read -p "Ingrese el nombre del archivo que quiere buscar: " nombre_archivo
    find . -name "$nombre_archivo"
}

function mover_archivo() {
    read -p "Ingrese el nombre del archivo que quiere mover: " nombre_archivo
    read -p "Ingrese el directorio al que quiere mover el archivo: " directorio_destino
    if [ -f "$nombre_archivo" ] && [ -d "$directorio_destino" ]; then
        mv "$nombre_archivo" "$directorio_destino"
        echo "Archivo '$nombre_archivo' movido a '$directorio_destino'."
    else
        echo "Archivo o directorio no encontrado"
    fi
}

function copiar_archivo() {
    read -p "Ingrese el nombre del archivo que quiere copiar: " nombre_archivo
    read -p "Ingrese el directorio al que quiere copiarlo: " directorio_destino
    if [ -f "$nombre_archivo" ] && [ -d "$directorio_destino" ]; then
        cp "$nombre_archivo" "$directorio_destino"
        echo "Archivo '$nombre_archivo' copiado a '$directorio_destino'."
    else
        echo "Archivo o directorio no encontrado"
    fi
}

while true; do
    mostrar_menu
    read -p "Opción: " opcion
    case $opcion in
        1) crear_directorio ;;
        2) listar_directorio ;;
        3) crear_archivo ;;
        4) ver_archivo ;;
        5) eliminar_archivo ;;
        6) codificar_base64 ;;
        7) decodificar_base64 ;;
        8) buscar_archivos ;;
        9) mover_archivo ;;
        10) copiar_archivo ;;
        11) echo "Saliendo"; exit 0 ;;
        *) echo "Opción no válida, por favor seleccione una opción del 1 al 11." ;;
    esac
done
